# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.all_same_num <- function(x) {
    .Call(`_seeutils_all_same_num`, x)
}

.all_same_char <- function(x) {
    .Call(`_seeutils_all_same_chr`, x)
}

